services:
  - type: web
    name: portfolio-yann-dipita
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: SMTP_USERNAME
        sync: false
      - key: SMTP_PASSWORD
        sync: false

